openapi: 3.1.0
x-stoplight:
  id: fi76hex04rsdu
info:
  title: Peach Media Services Response API
  version: '1.0'
  summary: API endpoints for the Mediaservices response to Peach
  description: 'A collection of API endpoints that handles the quality control, transcode and distribution rresponses from the Media Servers back to Peach.'
  contact:
    name: API Support
    url: 'https://api.peachvideo.com/support'
    email: partnerapi.support@peachvideo.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://db-mediaservices-response-api.imdcloud.net'
tags:
  - name: Quality Control
    description: Quality Control
paths:
  /qualitycontrol/v1/response:
    post:
      summary: Quality Control Callback
      operationId: post-qc
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: rjfzo39zvdtbv
              examples:
                Example 1:
                  value:
                    message: 'Missing required parameters: [result]'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: 38rmz9g35s56k
              examples:
                Example 1:
                  value:
                    message: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: edo5dl1lne034
              examples:
                Example 1:
                  value:
                    message: User is not authorized to access this resource
      description: Quality Control callback response from the Media Server upon completion of the QC process.
      security:
        - PeachApiKeyAuthentication: []
      parameters:
        - schema:
            type: string
          in: query
          name: traceId
          description: The TraceIdentifier coming from the workflow.
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
          description: The API Key that identifies the caller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QualityControl'
            examples:
              Successful QC Response:
                value:
                  metadata:
                    correlationId: a5e5f64f-53b3-4505-8767-c318c52732c2
                    status: Completed
                    note: QC_InternalWorkflow
                    serviceType: Quality Control
                  body:
                    result: '{"status":"Accepted","reportUrl":"https://db-mediaservices-api.imdcloud.net/qualitycontrol/v1/a5e5f64f-53b3-4505-8767-c318c52732c2/report","statusUrl":"https://db-mediaservices-api.imdcloud.net/qualitycontrol/v1/a5e5f64f-53b3-4505-8767-c318c52732c2/status"}'
              Failed QC Response:
                value:
                  metadata:
                    correlationId: a5e5f64f-53b3-4505-8767-c318c52732c2
                    status: Completed
                    note: QC_InternalWorkflow
                    serviceType: Quality Control
                  body:
                    result: '{"status":"Failed","reportUrl":"https://db-mediaservices-api.imdcloud.net/qualitycontrol/v1/a5e5f64f-53b3-4505-8767-c318c52732c2/report","statusUrl":"https://db-mediaservices-api.imdcloud.net/qualitycontrol/v1/a5e5f64f-53b3-4505-8767-c318c52732c2/status"}'
      tags:
        - Quality Control
    parameters: []
components:
  schemas:
    Metadata:
      title: Metadata
      x-stoplight:
        id: htdp9b81sizhh
      type: object
      properties:
        correlationId:
          type: string
          x-stoplight:
            id: fpjgte0y8wt21
          description: 'This is a unique reference to the resource. If this is a QC response, this will be the SubmissionId.'
        status:
          type: string
          x-stoplight:
            id: na2emk7xfu4h5
          description: 'Completed, InProgress, etc ...'
        note:
          type: string
          x-stoplight:
            id: 8k3w1dzbu6skn
          description: Additional information from the caller. This usually contains the type of service being returned.
        serviceType:
          type: string
          x-stoplight:
            id: 4mvvisjkzc9he
          description: 'Quality Control, Transcode or Distribution'
      description: The metadata detail included at the top of all response payloads
      examples:
        - correlationId: a5e5f64f-53b3-4505-8767-c318c52732c2
          status: Completed
          note: QC_InternalWorkflow
          serviceType: Quality Control
      x-tags:
        - Models
        - Common
    QualityControl:
      title: QualityControl
      x-stoplight:
        id: 5sfc5j1k45syi
      type: object
      examples:
        - metadata:
            correlationId: a5e5f64f-53b3-4505-8767-c318c52732c2
            status: Completed
            note: QC_InternalWorkflow
            serviceType: Quality Control
          body:
            result: '{"status":"Accepted","reportUrl":"https://db-mediaservices-api.imdcloud.net/qualitycontrol/v1/a5e5f64f-53b3-4505-8767-c318c52732c2/report","statusUrl":"https://db-mediaservices-api.imdcloud.net/qualitycontrol/v1/a5e5f64f-53b3-4505-8767-c318c52732c2/status"}'
      properties:
        metadata:
          $ref: '#/components/schemas/Metadata'
          x-stoplight:
            id: 1yghwy0gazlid
        body:
          type: object
          x-stoplight:
            id: 9cyv09kllceyy
          required:
            - result
          properties:
            result:
              type: string
              x-stoplight:
                id: 3y6bd8dbnhslj
              description: This contains a JSON encoded string containing the report url and the status url of the QC Submission.
      required:
        - body
      x-tags:
        - Models
        - Quality Control
  securitySchemes:
    PeachApiKeyAuthentication:
      name: Authorization
      type: apiKey
      in: header
security:
  - PeachApiKeyAuthentication: []
